// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(WebDbContext))]
    partial class WebDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Cultivar.Cultivars", b =>
                {
                    b.Property<Guid>("CultivarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CultivarName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TreeTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CultivarId");

                    b.HasIndex("TreeTypeId");

                    b.ToTable("Cultivars", (string)null);

                    b.HasData(
                        new
                        {
                            CultivarId = new Guid("136514ac-99a2-421a-80e1-5351d9a9c4af"),
                            CreateBy = "Admin",
                            CreateDate = new DateTime(2024, 3, 9, 0, 47, 2, 692, DateTimeKind.Local).AddTicks(6084),
                            CultivarName = "Giong cay bang",
                            TreeTypeId = new Guid("ad98e780-ce3b-401b-a2ec-dd7ba8027642"),
                            UpdateBy = "Admin",
                            UpdateDate = new DateTime(2024, 3, 9, 0, 47, 2, 692, DateTimeKind.Local).AddTicks(6085)
                        },
                        new
                        {
                            CultivarId = new Guid("136514ac-99a2-221a-80e1-5351d9a9c4af"),
                            CreateBy = "Admin",
                            CreateDate = new DateTime(2024, 3, 9, 0, 47, 2, 692, DateTimeKind.Local).AddTicks(6108),
                            CultivarName = "Giong cay phuong",
                            TreeTypeId = new Guid("ad98e780-ce3b-401b-a2ec-dd7ba8027642"),
                            UpdateBy = "Admin",
                            UpdateDate = new DateTime(2024, 3, 9, 0, 47, 2, 692, DateTimeKind.Local).AddTicks(6109)
                        });
                });

            modelBuilder.Entity("Domain.Entities.Deparment.Departments", b =>
                {
                    b.Property<Guid>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments", (string)null);

                    b.HasData(
                        new
                        {
                            DepartmentId = new Guid("bc2f24de-2b9b-489a-a108-64a114d2b9be"),
                            CreateBy = "Admin",
                            CreateDate = new DateTime(2024, 3, 9, 0, 47, 2, 692, DateTimeKind.Local).AddTicks(9483),
                            DepartmentName = "Quet don via he",
                            UpdateBy = "Admin",
                            UpdateDate = new DateTime(2024, 3, 9, 0, 47, 2, 692, DateTimeKind.Local).AddTicks(9484)
                        },
                        new
                        {
                            DepartmentId = new Guid("bc2f24de-2b9b-429a-a108-64a114d2b9be"),
                            CreateBy = "Admin",
                            CreateDate = new DateTime(2024, 3, 9, 0, 47, 2, 692, DateTimeKind.Local).AddTicks(9502),
                            DepartmentName = "Thu gom rac",
                            UpdateBy = "Admin",
                            UpdateDate = new DateTime(2024, 3, 9, 0, 47, 2, 692, DateTimeKind.Local).AddTicks(9503)
                        },
                        new
                        {
                            DepartmentId = new Guid("bc2f24de-1b9b-489a-a108-64a114d2b9be"),
                            CreateBy = "Admin",
                            CreateDate = new DateTime(2024, 3, 9, 0, 47, 2, 692, DateTimeKind.Local).AddTicks(9508),
                            DepartmentName = "Cat tia cay",
                            UpdateBy = "Admin",
                            UpdateDate = new DateTime(2024, 3, 9, 0, 47, 2, 692, DateTimeKind.Local).AddTicks(9509)
                        });
                });

            modelBuilder.Entity("Domain.Entities.District.Districts", b =>
                {
                    b.Property<Guid>("DistrictId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DistrictName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("DistrictId");

                    b.ToTable("Districts", (string)null);

                    b.HasData(
                        new
                        {
                            DistrictId = new Guid("be7d62da-53ea-46b0-b294-bb109eca92fc"),
                            CreateBy = "Admin",
                            CreateDate = new DateTime(2024, 3, 9, 0, 47, 2, 693, DateTimeKind.Local).AddTicks(2102),
                            DistrictName = "Ngu Hanh Son",
                            UpdateBy = "Admin",
                            UpdateDate = new DateTime(2024, 3, 9, 0, 47, 2, 693, DateTimeKind.Local).AddTicks(2104)
                        },
                        new
                        {
                            DistrictId = new Guid("be7d62da-33ea-46b0-b294-bb109eca92fc"),
                            CreateBy = "Admin",
                            CreateDate = new DateTime(2024, 3, 9, 0, 47, 2, 693, DateTimeKind.Local).AddTicks(2122),
                            DistrictName = "Thanh Khe",
                            UpdateBy = "Admin",
                            UpdateDate = new DateTime(2024, 3, 9, 0, 47, 2, 693, DateTimeKind.Local).AddTicks(2123)
                        },
                        new
                        {
                            DistrictId = new Guid("be7d62da-51ea-46b0-b294-bb109eca92fc"),
                            CreateBy = "Admin",
                            CreateDate = new DateTime(2024, 3, 9, 0, 47, 2, 693, DateTimeKind.Local).AddTicks(2127),
                            DistrictName = "Hai Chau",
                            UpdateBy = "Admin",
                            UpdateDate = new DateTime(2024, 3, 9, 0, 47, 2, 693, DateTimeKind.Local).AddTicks(2128)
                        });
                });

            modelBuilder.Entity("Domain.Entities.Report.Reports", b =>
                {
                    b.Property<Guid>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Feedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeedbackBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ReportId");

                    b.HasIndex("UserId");

                    b.ToTable("Reports", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ResidentialGroup.ResidentialGroups", b =>
                {
                    b.Property<Guid>("ResidentialGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResidentialGroupName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WardId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ResidentialGroupId");

                    b.HasIndex("WardId");

                    b.ToTable("ResidentialGroups", (string)null);

                    b.HasData(
                        new
                        {
                            ResidentialGroupId = new Guid("0a0e931d-d055-48a9-b8a4-2cf57ac2f6f5"),
                            CreateBy = "Admin",
                            CreateDate = new DateTime(2024, 3, 9, 0, 47, 2, 693, DateTimeKind.Local).AddTicks(7112),
                            ResidentialGroupName = "Dong Tra",
                            UpdateBy = "Admin",
                            UpdateDate = new DateTime(2024, 3, 9, 0, 47, 2, 693, DateTimeKind.Local).AddTicks(7113),
                            WardId = new Guid("996c63bc-5f0a-44f6-8c9a-aad741b3beac")
                        });
                });

            modelBuilder.Entity("Domain.Entities.Role.Roles", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("RoleId");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("abccde85-c7dc-4f78-9e4e-b1b3e7abee84"),
                            CreateBy = "Admin",
                            CreateDate = new DateTime(2024, 3, 9, 0, 47, 2, 694, DateTimeKind.Local).AddTicks(58),
                            RoleName = "Manager",
                            UpdateBy = "Admin",
                            UpdateDate = new DateTime(2024, 3, 9, 0, 47, 2, 694, DateTimeKind.Local).AddTicks(59)
                        },
                        new
                        {
                            RoleId = new Guid("cacd4b3a-8afe-43e9-b757-f57f5c61f8d8"),
                            CreateBy = "Admin",
                            CreateDate = new DateTime(2024, 3, 9, 0, 47, 2, 694, DateTimeKind.Local).AddTicks(142),
                            RoleName = "Leader",
                            UpdateBy = "Admin",
                            UpdateDate = new DateTime(2024, 3, 9, 0, 47, 2, 694, DateTimeKind.Local).AddTicks(144)
                        },
                        new
                        {
                            RoleId = new Guid("8977ef77-e554-4ef3-8353-3e01161f84d0"),
                            CreateBy = "Admin",
                            CreateDate = new DateTime(2024, 3, 9, 0, 47, 2, 694, DateTimeKind.Local).AddTicks(150),
                            RoleName = "Employee",
                            UpdateBy = "Admin",
                            UpdateDate = new DateTime(2024, 3, 9, 0, 47, 2, 694, DateTimeKind.Local).AddTicks(151)
                        });
                });

            modelBuilder.Entity("Domain.Entities.Street.Streets", b =>
                {
                    b.Property<Guid>("StreetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumberOfHouses")
                        .HasColumnType("int");

                    b.Property<Guid>("ResidentialGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("StreetLength")
                        .HasColumnType("real");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("StreetTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("StreetId");

                    b.HasIndex("ResidentialGroupId");

                    b.HasIndex("StreetTypeId");

                    b.ToTable("Streets", (string)null);

                    b.HasData(
                        new
                        {
                            StreetId = new Guid("0c0187dc-c7e2-4aa9-ae35-a5e2d60dfa24"),
                            CreateBy = "Admin",
                            CreateDate = new DateTime(2024, 3, 9, 0, 47, 2, 694, DateTimeKind.Local).AddTicks(3393),
                            NumberOfHouses = 20,
                            ResidentialGroupId = new Guid("0a0e931d-d055-48a9-b8a4-2cf57ac2f6f5"),
                            StreetLength = 10000f,
                            StreetName = "Duong Huynh Lam",
                            StreetTypeId = new Guid("1be73957-b7e9-4304-9242-00e8b92a86f0"),
                            UpdateBy = "Admin",
                            UpdateDate = new DateTime(2024, 3, 9, 0, 47, 2, 694, DateTimeKind.Local).AddTicks(3394)
                        });
                });

            modelBuilder.Entity("Domain.Entities.StreetType.StreetTypes", b =>
                {
                    b.Property<Guid>("StreetTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StreetTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("StreetTypeId");

                    b.ToTable("StreetTypes", (string)null);

                    b.HasData(
                        new
                        {
                            StreetTypeId = new Guid("1be73957-b7e9-4304-9242-00e8b92a86f0"),
                            CreateBy = "Admin",
                            CreateDate = new DateTime(2024, 3, 9, 0, 47, 2, 694, DateTimeKind.Local).AddTicks(5756),
                            StreetTypeName = "Duong Kinh Doanh",
                            UpdateBy = "Admin",
                            UpdateDate = new DateTime(2024, 3, 9, 0, 47, 2, 694, DateTimeKind.Local).AddTicks(5757)
                        },
                        new
                        {
                            StreetTypeId = new Guid("e3d44b7e-8ebe-434f-88ef-054a81951be1"),
                            CreateBy = "Admin",
                            CreateDate = new DateTime(2024, 3, 9, 0, 47, 2, 694, DateTimeKind.Local).AddTicks(5775),
                            StreetTypeName = "Duong Dan Sinh",
                            UpdateBy = "Admin",
                            UpdateDate = new DateTime(2024, 3, 9, 0, 47, 2, 694, DateTimeKind.Local).AddTicks(5776)
                        });
                });

            modelBuilder.Entity("Domain.Entities.Tree.Trees", b =>
                {
                    b.Property<Guid>("TreeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("BodyDiameter")
                        .HasColumnType("real");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CultivarId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CutTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("IntervalCutTime")
                        .HasColumnType("int");

                    b.Property<float>("LeafLength")
                        .HasColumnType("real");

                    b.Property<string>("Note")
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<DateTime>("PlantTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("StreetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TreeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isCut")
                        .HasColumnType("bit");

                    b.Property<bool>("isExist")
                        .HasColumnType("bit");

                    b.HasKey("TreeId");

                    b.HasIndex("CultivarId");

                    b.HasIndex("StreetId");

                    b.ToTable("Trees", (string)null);

                    b.HasData(
                        new
                        {
                            TreeId = new Guid("24b2ee45-d7c3-4cc7-9fac-406b4bac1d82"),
                            BodyDiameter = 30f,
                            CreateBy = "Admin",
                            CreateDate = new DateTime(2024, 3, 9, 0, 47, 2, 694, DateTimeKind.Local).AddTicks(8315),
                            CultivarId = new Guid("136514ac-99a2-421a-80e1-5351d9a9c4af"),
                            CutTime = new DateTime(2024, 6, 9, 0, 47, 2, 694, DateTimeKind.Local).AddTicks(8270),
                            IntervalCutTime = 3,
                            LeafLength = 50f,
                            Note = "",
                            PlantTime = new DateTime(2024, 3, 9, 0, 47, 2, 694, DateTimeKind.Local).AddTicks(8269),
                            StreetId = new Guid("0c0187dc-c7e2-4aa9-ae35-a5e2d60dfa24"),
                            TreeCode = "12_HL_HH_NHS",
                            UpdateBy = "Admin",
                            UpdateDate = new DateTime(2024, 3, 9, 0, 47, 2, 694, DateTimeKind.Local).AddTicks(8317),
                            isCut = true,
                            isExist = true
                        });
                });

            modelBuilder.Entity("Domain.Entities.TreeType.TreeTypes", b =>
                {
                    b.Property<Guid>("TreeTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TreeTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("TreeTypeId");

                    b.ToTable("TreeTypes", (string)null);

                    b.HasData(
                        new
                        {
                            TreeTypeId = new Guid("ad98e780-ce3b-401b-a2ec-dd7ba8027642"),
                            CreateBy = "Admin",
                            CreateDate = new DateTime(2024, 3, 9, 0, 47, 2, 695, DateTimeKind.Local).AddTicks(814),
                            TreeTypeName = "Cay than go",
                            UpdateBy = "Admin",
                            UpdateDate = new DateTime(2024, 3, 9, 0, 47, 2, 695, DateTimeKind.Local).AddTicks(815)
                        });
                });

            modelBuilder.Entity("Domain.Entities.User.Users", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.UserRefreshToken.UserRefreshTokens", b =>
                {
                    b.Property<Guid>("UserRefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("Expire")
                        .HasColumnType("bigint");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserRefreshTokenId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRefreshTokens", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Ward.Wards", b =>
                {
                    b.Property<Guid>("WardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DistrictId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WardName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("WardId");

                    b.HasIndex("DistrictId");

                    b.ToTable("Wards", (string)null);

                    b.HasData(
                        new
                        {
                            WardId = new Guid("996c63bc-5f0a-44f6-8c9a-aad741b3beac"),
                            DistrictId = new Guid("be7d62da-53ea-46b0-b294-bb109eca92fc"),
                            WardName = "Hoa Hai"
                        },
                        new
                        {
                            WardId = new Guid("faa64719-904b-4844-9ec9-d8f2620ffb51"),
                            DistrictId = new Guid("be7d62da-53ea-46b0-b294-bb109eca92fc"),
                            WardName = "Khue My"
                        },
                        new
                        {
                            WardId = new Guid("79bea4b4-23ce-41ad-b585-4dfc835d607a"),
                            DistrictId = new Guid("be7d62da-53ea-46b0-b294-bb109eca92fc"),
                            WardName = "Hoa Quy"
                        },
                        new
                        {
                            WardId = new Guid("38af1dbf-b83f-4899-8389-743021c463a0"),
                            DistrictId = new Guid("be7d62da-53ea-46b0-b294-bb109eca92fc"),
                            WardName = "My An"
                        },
                        new
                        {
                            WardId = new Guid("c088acde-18ea-48ca-ae03-bdd4e610e039"),
                            DistrictId = new Guid("be7d62da-53ea-46b0-b294-bb109eca92fc"),
                            WardName = "Hai Chau I"
                        },
                        new
                        {
                            WardId = new Guid("3097108f-15fe-4ac8-aab4-187b56841c81"),
                            DistrictId = new Guid("be7d62da-53ea-46b0-b294-bb109eca92fc"),
                            WardName = "Hai Chau II"
                        },
                        new
                        {
                            WardId = new Guid("f4e93702-9dc2-4288-8f23-4c3812ed50cc"),
                            DistrictId = new Guid("be7d62da-53ea-46b0-b294-bb109eca92fc"),
                            WardName = "Thuan Phuoc"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Cultivar.Cultivars", b =>
                {
                    b.HasOne("Domain.Entities.TreeType.TreeTypes", "TreeTypes")
                        .WithMany("Cultivars")
                        .HasForeignKey("TreeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TreeTypes");
                });

            modelBuilder.Entity("Domain.Entities.Report.Reports", b =>
                {
                    b.HasOne("Domain.Entities.User.Users", "Users")
                        .WithMany("Reports")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Entities.ResidentialGroup.ResidentialGroups", b =>
                {
                    b.HasOne("Domain.Entities.Ward.Wards", "Ward")
                        .WithMany("ResidentialGroups")
                        .HasForeignKey("WardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("Domain.Entities.Street.Streets", b =>
                {
                    b.HasOne("Domain.Entities.ResidentialGroup.ResidentialGroups", "ResidentialGroup")
                        .WithMany("Streets")
                        .HasForeignKey("ResidentialGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.StreetType.StreetTypes", "StreetType")
                        .WithMany("Streets")
                        .HasForeignKey("StreetTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResidentialGroup");

                    b.Navigation("StreetType");
                });

            modelBuilder.Entity("Domain.Entities.Tree.Trees", b =>
                {
                    b.HasOne("Domain.Entities.Cultivar.Cultivars", "Cultivar")
                        .WithMany("Trees")
                        .HasForeignKey("CultivarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Street.Streets", "Streets")
                        .WithMany("Trees")
                        .HasForeignKey("StreetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cultivar");

                    b.Navigation("Streets");
                });

            modelBuilder.Entity("Domain.Entities.User.Users", b =>
                {
                    b.HasOne("Domain.Entities.Deparment.Departments", "Departments")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Role.Roles", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departments");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Entities.UserRefreshToken.UserRefreshTokens", b =>
                {
                    b.HasOne("Domain.Entities.User.Users", "User")
                        .WithMany("UserRefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Ward.Wards", b =>
                {
                    b.HasOne("Domain.Entities.District.Districts", "Districts")
                        .WithMany("Wards")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Districts");
                });

            modelBuilder.Entity("Domain.Entities.Cultivar.Cultivars", b =>
                {
                    b.Navigation("Trees");
                });

            modelBuilder.Entity("Domain.Entities.Deparment.Departments", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Entities.District.Districts", b =>
                {
                    b.Navigation("Wards");
                });

            modelBuilder.Entity("Domain.Entities.ResidentialGroup.ResidentialGroups", b =>
                {
                    b.Navigation("Streets");
                });

            modelBuilder.Entity("Domain.Entities.Role.Roles", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Entities.Street.Streets", b =>
                {
                    b.Navigation("Trees");
                });

            modelBuilder.Entity("Domain.Entities.StreetType.StreetTypes", b =>
                {
                    b.Navigation("Streets");
                });

            modelBuilder.Entity("Domain.Entities.TreeType.TreeTypes", b =>
                {
                    b.Navigation("Cultivars");
                });

            modelBuilder.Entity("Domain.Entities.User.Users", b =>
                {
                    b.Navigation("Reports");

                    b.Navigation("UserRefreshTokens");
                });

            modelBuilder.Entity("Domain.Entities.Ward.Wards", b =>
                {
                    b.Navigation("ResidentialGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
