// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(WebDbContext))]
    partial class WebDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.BucketTruck.BucketTrucks", b =>
                {
                    b.Property<Guid>("BucketTruckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BucketTruckLicensePlates")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<float>("CraneArmLength")
                        .HasColumnType("real");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("BucketTruckId");

                    b.ToTable("Bucket Trucks", (string)null);

                    b.HasData(
                        new
                        {
                            BucketTruckId = new Guid("f9257e9f-6d30-45fd-8afc-3e3266d7adc6"),
                            BucketTruckLicensePlates = "123123123Aa",
                            CraneArmLength = 12f,
                            CreateBy = "Admin",
                            CreateDate = new DateTime(2024, 1, 15, 17, 8, 48, 392, DateTimeKind.Local).AddTicks(832),
                            UpdateBy = "Admin",
                            UpdateDate = new DateTime(2024, 1, 15, 17, 8, 48, 392, DateTimeKind.Local).AddTicks(833)
                        },
                        new
                        {
                            BucketTruckId = new Guid("f9257e9f-6d31-45fd-8afc-3e3266d7adc6"),
                            BucketTruckLicensePlates = "123123123Aa",
                            CraneArmLength = 12f,
                            CreateBy = "Admin",
                            CreateDate = new DateTime(2024, 1, 15, 17, 8, 48, 392, DateTimeKind.Local).AddTicks(846),
                            UpdateBy = "Admin",
                            UpdateDate = new DateTime(2024, 1, 15, 17, 8, 48, 392, DateTimeKind.Local).AddTicks(846)
                        });
                });

            modelBuilder.Entity("Domain.Entities.Cultivar.Cultivars", b =>
                {
                    b.Property<Guid>("CultivarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CultivarName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TreeTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CultivarId");

                    b.HasIndex("TreeTypeId");

                    b.ToTable("Cultivars", (string)null);

                    b.HasData(
                        new
                        {
                            CultivarId = new Guid("136514ac-99a2-421a-80e1-5351d9a9c4af"),
                            CreateBy = "Admin",
                            CreateDate = new DateTime(2024, 1, 15, 17, 8, 48, 392, DateTimeKind.Local).AddTicks(2550),
                            CultivarName = "Giong cay bang",
                            TreeTypeId = new Guid("ad98e780-ce3b-401b-a2ec-dd7ba8027642"),
                            UpdateBy = "Admin",
                            UpdateDate = new DateTime(2024, 1, 15, 17, 8, 48, 392, DateTimeKind.Local).AddTicks(2550)
                        },
                        new
                        {
                            CultivarId = new Guid("136514ac-99a2-221a-80e1-5351d9a9c4af"),
                            CreateBy = "Admin",
                            CreateDate = new DateTime(2024, 1, 15, 17, 8, 48, 392, DateTimeKind.Local).AddTicks(2564),
                            CultivarName = "Giong cay phuong",
                            TreeTypeId = new Guid("ad98e780-ce3b-401b-a2ec-dd7ba8027642"),
                            UpdateBy = "Admin",
                            UpdateDate = new DateTime(2024, 1, 15, 17, 8, 48, 392, DateTimeKind.Local).AddTicks(2565)
                        });
                });

            modelBuilder.Entity("Domain.Entities.Deparment.Departments", b =>
                {
                    b.Property<Guid>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments", (string)null);

                    b.HasData(
                        new
                        {
                            DepartmentId = new Guid("bc2f24de-2b9b-489a-a108-64a114d2b9be"),
                            CreateBy = "Admin",
                            CreateDate = new DateTime(2024, 1, 15, 17, 8, 48, 392, DateTimeKind.Local).AddTicks(4356),
                            DepartmentName = "Quet don via he",
                            UpdateBy = "Admin",
                            UpdateDate = new DateTime(2024, 1, 15, 17, 8, 48, 392, DateTimeKind.Local).AddTicks(4357)
                        },
                        new
                        {
                            DepartmentId = new Guid("bc2f24de-2b9b-429a-a108-64a114d2b9be"),
                            CreateBy = "Admin",
                            CreateDate = new DateTime(2024, 1, 15, 17, 8, 48, 392, DateTimeKind.Local).AddTicks(4370),
                            DepartmentName = "Thu gom rac",
                            UpdateBy = "Admin",
                            UpdateDate = new DateTime(2024, 1, 15, 17, 8, 48, 392, DateTimeKind.Local).AddTicks(4371)
                        },
                        new
                        {
                            DepartmentId = new Guid("bc2f24de-1b9b-489a-a108-64a114d2b9be"),
                            CreateBy = "Admin",
                            CreateDate = new DateTime(2024, 1, 15, 17, 8, 48, 392, DateTimeKind.Local).AddTicks(4375),
                            DepartmentName = "Cat tia cay",
                            UpdateBy = "Admin",
                            UpdateDate = new DateTime(2024, 1, 15, 17, 8, 48, 392, DateTimeKind.Local).AddTicks(4375)
                        });
                });

            modelBuilder.Entity("Domain.Entities.District.Districts", b =>
                {
                    b.Property<Guid>("DistrictId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DistrictName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("DistrictId");

                    b.ToTable("Districts", (string)null);

                    b.HasData(
                        new
                        {
                            DistrictId = new Guid("be7d62da-53ea-46b0-b294-bb109eca92fc"),
                            CreateBy = "Admin",
                            CreateDate = new DateTime(2024, 1, 15, 17, 8, 48, 392, DateTimeKind.Local).AddTicks(5802),
                            DistrictName = "Ngu Hanh Son",
                            UpdateBy = "Admin",
                            UpdateDate = new DateTime(2024, 1, 15, 17, 8, 48, 392, DateTimeKind.Local).AddTicks(5803)
                        },
                        new
                        {
                            DistrictId = new Guid("be7d62da-33ea-46b0-b294-bb109eca92fc"),
                            CreateBy = "Admin",
                            CreateDate = new DateTime(2024, 1, 15, 17, 8, 48, 392, DateTimeKind.Local).AddTicks(5813),
                            DistrictName = "Thanh Khe",
                            UpdateBy = "Admin",
                            UpdateDate = new DateTime(2024, 1, 15, 17, 8, 48, 392, DateTimeKind.Local).AddTicks(5814)
                        },
                        new
                        {
                            DistrictId = new Guid("be7d62da-51ea-46b0-b294-bb109eca92fc"),
                            CreateBy = "Admin",
                            CreateDate = new DateTime(2024, 1, 15, 17, 8, 48, 392, DateTimeKind.Local).AddTicks(5818),
                            DistrictName = "Hai Chau",
                            UpdateBy = "Admin",
                            UpdateDate = new DateTime(2024, 1, 15, 17, 8, 48, 392, DateTimeKind.Local).AddTicks(5818)
                        });
                });

            modelBuilder.Entity("Domain.Entities.GarbageDump.GarbageDumps", b =>
                {
                    b.Property<Guid>("GarbageDumpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GarbageDumpName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("StreetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("WardsWardId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GarbageDumpId");

                    b.HasIndex("StreetId");

                    b.HasIndex("WardsWardId");

                    b.ToTable("GarbageDumps", (string)null);

                    b.HasData(
                        new
                        {
                            GarbageDumpId = new Guid("be5d01ee-b15c-4ced-aa0c-165c47dac9f9"),
                            CreateBy = "Admin",
                            CreateDate = new DateTime(2024, 1, 15, 17, 8, 48, 392, DateTimeKind.Local).AddTicks(7663),
                            GarbageDumpName = "HL-HH-NHS_1",
                            StreetId = new Guid("0c0187dc-c7e2-4aa9-ae35-a5e2d60dfa24"),
                            UpdateBy = "Admin",
                            UpdateDate = new DateTime(2024, 1, 15, 17, 8, 48, 392, DateTimeKind.Local).AddTicks(7663)
                        },
                        new
                        {
                            GarbageDumpId = new Guid("be5d01ee-b15d-4ced-aa0c-165c47dac9f9"),
                            CreateBy = "Admin",
                            CreateDate = new DateTime(2024, 1, 15, 17, 8, 48, 392, DateTimeKind.Local).AddTicks(7676),
                            GarbageDumpName = "HL-HH-NHS_2",
                            StreetId = new Guid("0c0187dc-c7e2-4aa9-ae35-a5e2d60dfa24"),
                            UpdateBy = "Admin",
                            UpdateDate = new DateTime(2024, 1, 15, 17, 8, 48, 392, DateTimeKind.Local).AddTicks(7677)
                        });
                });

            modelBuilder.Entity("Domain.Entities.GarbageTruck.GarbageTrucks", b =>
                {
                    b.Property<Guid>("GarbageTruckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GarbageDumpId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GarbageTruckLicensePlates")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GarbageTruckTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("GarbageTruckWeight")
                        .HasColumnType("real");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("GarbageTruckId");

                    b.HasIndex("GarbageDumpId");

                    b.HasIndex("GarbageTruckTypeId");

                    b.ToTable("GarbageTrucks", (string)null);

                    b.HasData(
                        new
                        {
                            GarbageTruckId = new Guid("fc34e805-4550-4037-a273-17a0b1639bbe"),
                            CreateBy = "Admin",
                            CreateDate = new DateTime(2024, 1, 15, 17, 8, 48, 392, DateTimeKind.Local).AddTicks(9688),
                            GarbageDumpId = new Guid("be5d01ee-b15c-4ced-aa0c-165c47dac9f9"),
                            GarbageTruckLicensePlates = "123123Aa",
                            GarbageTruckTypeId = new Guid("12e42a48-f991-4733-bd7c-2e536f931b22"),
                            GarbageTruckWeight = 450f,
                            UpdateBy = "Admin",
                            UpdateDate = new DateTime(2024, 1, 15, 17, 8, 48, 392, DateTimeKind.Local).AddTicks(9690)
                        },
                        new
                        {
                            GarbageTruckId = new Guid("fc34e805-4550-4037-a273-17a0b1639bbc"),
                            CreateBy = "Admin",
                            CreateDate = new DateTime(2024, 1, 15, 17, 8, 48, 392, DateTimeKind.Local).AddTicks(9702),
                            GarbageDumpId = new Guid("be5d01ee-b15c-4ced-aa0c-165c47dac9f9"),
                            GarbageTruckLicensePlates = "123456Aa",
                            GarbageTruckTypeId = new Guid("12e42a48-f991-4733-bd7c-2e536f931b22"),
                            GarbageTruckWeight = 450f,
                            UpdateBy = "Admin",
                            UpdateDate = new DateTime(2024, 1, 15, 17, 8, 48, 392, DateTimeKind.Local).AddTicks(9703)
                        });
                });

            modelBuilder.Entity("Domain.Entities.GarbageTruckType.GarbageTruckTypes", b =>
                {
                    b.Property<Guid>("GarbageTruckTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GarbageTruckTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("GarbageTruckTypeId");

                    b.ToTable("GarbageTruckTypes", (string)null);

                    b.HasData(
                        new
                        {
                            GarbageTruckTypeId = new Guid("12e42a48-f991-4733-bd7c-2e536f931b22"),
                            CreateBy = "Admin",
                            CreateDate = new DateTime(2024, 1, 15, 17, 8, 48, 393, DateTimeKind.Local).AddTicks(1229),
                            GarbageTruckTypeName = "Xe thu gom rac nho",
                            UpdateBy = "Admin",
                            UpdateDate = new DateTime(2024, 1, 15, 17, 8, 48, 393, DateTimeKind.Local).AddTicks(1230)
                        },
                        new
                        {
                            GarbageTruckTypeId = new Guid("12e42a48-f991-4733-bd7c-2e536f921b22"),
                            CreateBy = "Admin",
                            CreateDate = new DateTime(2024, 1, 15, 17, 8, 48, 393, DateTimeKind.Local).AddTicks(1279),
                            GarbageTruckTypeName = "Xe thu gom rac to",
                            UpdateBy = "Admin",
                            UpdateDate = new DateTime(2024, 1, 15, 17, 8, 48, 393, DateTimeKind.Local).AddTicks(1279)
                        });
                });

            modelBuilder.Entity("Domain.Entities.ListGarbagemanTask.ListGarbagemanTasks", b =>
                {
                    b.Property<Guid>("ListGarbagemanTaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ScheduleGarbageCollectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ListGarbagemanTaskId");

                    b.HasIndex("ScheduleGarbageCollectId");

                    b.HasIndex("UserId");

                    b.ToTable("ListGarbagemanTasks", (string)null);

                    b.HasData(
                        new
                        {
                            ListGarbagemanTaskId = new Guid("f348026b-3f20-4197-865f-076f47c4cbc7"),
                            CreateBy = "Admin",
                            CreateDate = new DateTime(2024, 1, 15, 17, 8, 48, 393, DateTimeKind.Local).AddTicks(2218),
                            ScheduleGarbageCollectId = new Guid("26397b2b-ca94-4af4-bf0d-f7aaa7510698"),
                            UpdateBy = "Admin",
                            UpdateDate = new DateTime(2024, 1, 15, 17, 8, 48, 393, DateTimeKind.Local).AddTicks(2219),
                            UserId = new Guid("b2b1e0ce-0187-4285-8cce-60fdff665f46")
                        },
                        new
                        {
                            ListGarbagemanTaskId = new Guid("f348026b-3f20-4197-865f-076f47c4cbd7"),
                            CreateBy = "Admin",
                            CreateDate = new DateTime(2024, 1, 15, 17, 8, 48, 393, DateTimeKind.Local).AddTicks(2230),
                            ScheduleGarbageCollectId = new Guid("26397b2b-ca94-4af4-bf0d-f7aaa7510698"),
                            UpdateBy = "Admin",
                            UpdateDate = new DateTime(2024, 1, 15, 17, 8, 48, 393, DateTimeKind.Local).AddTicks(2231),
                            UserId = new Guid("b2b1e0ce-0187-4285-8cce-60fdff666f46")
                        });
                });

            modelBuilder.Entity("Domain.Entities.ListSidewalkCleanerTask.ListSidewalkCleanerTasks", b =>
                {
                    b.Property<Guid>("ListSidewalkCleanerTaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ScheduleCleanSidewalkId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ListSidewalkCleanerTaskId");

                    b.HasIndex("ScheduleCleanSidewalkId");

                    b.HasIndex("UserId");

                    b.ToTable("ListSidewalkCleanerTasks", (string)null);

                    b.HasData(
                        new
                        {
                            ListSidewalkCleanerTaskId = new Guid("3c30019e-05f6-4f43-8bd5-3e29ef9004cf"),
                            CreateBy = "Admin",
                            CreateDate = new DateTime(2024, 1, 15, 17, 8, 48, 393, DateTimeKind.Local).AddTicks(3194),
                            ScheduleCleanSidewalkId = new Guid("7a866c85-b013-4fab-80c7-15d21d0c686c"),
                            UpdateBy = "Admin",
                            UpdateDate = new DateTime(2024, 1, 15, 17, 8, 48, 393, DateTimeKind.Local).AddTicks(3195),
                            UserId = new Guid("b2b1e0ce-0187-4285-8cce-60fdff665f46")
                        },
                        new
                        {
                            ListSidewalkCleanerTaskId = new Guid("3c30019e-05f6-4f43-8bd5-3e29ef90031a"),
                            CreateBy = "Admin",
                            CreateDate = new DateTime(2024, 1, 15, 17, 8, 48, 393, DateTimeKind.Local).AddTicks(3207),
                            ScheduleCleanSidewalkId = new Guid("7a866c85-b013-4fab-80c7-15d21d0c686c"),
                            UpdateBy = "Admin",
                            UpdateDate = new DateTime(2024, 1, 15, 17, 8, 48, 393, DateTimeKind.Local).AddTicks(3207),
                            UserId = new Guid("b2b1e0ce-0187-4285-8cce-60fdff666f46")
                        });
                });

            modelBuilder.Entity("Domain.Entities.ListTreeTrimmerTask.ListTreeTrimmerTasks", b =>
                {
                    b.Property<Guid>("ListTreeTrimmerTaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ScheduleTreeTrimId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ListTreeTrimmerTaskId");

                    b.HasIndex("ScheduleTreeTrimId");

                    b.HasIndex("UserId");

                    b.ToTable("ListTreeTrimmerTasks", (string)null);

                    b.HasData(
                        new
                        {
                            ListTreeTrimmerTaskId = new Guid("25f83ff6-39d4-461d-82d3-3814cb57fa9c"),
                            CreateBy = "Admin",
                            CreateDate = new DateTime(2024, 1, 15, 17, 8, 48, 393, DateTimeKind.Local).AddTicks(4152),
                            ScheduleTreeTrimId = new Guid("04dc28f5-94c4-4565-93a2-934d6fee53fd"),
                            UpdateBy = "Admin",
                            UpdateDate = new DateTime(2024, 1, 15, 17, 8, 48, 393, DateTimeKind.Local).AddTicks(4154),
                            UserId = new Guid("b2b1e0ce-0187-4285-8cce-60fdff665f46")
                        },
                        new
                        {
                            ListTreeTrimmerTaskId = new Guid("e13c54c5-1923-49ef-99ab-54a60fed579c"),
                            CreateBy = "Admin",
                            CreateDate = new DateTime(2024, 1, 15, 17, 8, 48, 393, DateTimeKind.Local).AddTicks(4165),
                            ScheduleTreeTrimId = new Guid("04dc28f5-94c4-4565-93a2-934d6fee53fd"),
                            UpdateBy = "Admin",
                            UpdateDate = new DateTime(2024, 1, 15, 17, 8, 48, 393, DateTimeKind.Local).AddTicks(4166),
                            UserId = new Guid("b2b1e0ce-0187-4285-8cce-60fdff666f46")
                        });
                });

            modelBuilder.Entity("Domain.Entities.Report.Reports", b =>
                {
                    b.Property<Guid>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Feedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeedbackBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ReportId");

                    b.HasIndex("UserId");

                    b.ToTable("Reports", (string)null);

                    b.HasData(
                        new
                        {
                            ReportId = new Guid("6e4ba4c3-6edf-45ca-8b60-54caa256c725"),
                            Content = "Demo",
                            Image = "string",
                            Status = false,
                            Title = "DEMO",
                            UserId = new Guid("b2b1e0ce-0187-4285-8cce-60fdff665f46")
                        });
                });

            modelBuilder.Entity("Domain.Entities.Role.Roles", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("RoleId");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("abccde85-c7dc-4f78-9e4e-b1b3e7abee84"),
                            CreateBy = "Admin",
                            CreateDate = new DateTime(2024, 1, 15, 17, 8, 48, 393, DateTimeKind.Local).AddTicks(6837),
                            RoleName = "Manager",
                            UpdateBy = "Admin",
                            UpdateDate = new DateTime(2024, 1, 15, 17, 8, 48, 393, DateTimeKind.Local).AddTicks(6838)
                        },
                        new
                        {
                            RoleId = new Guid("cacd4b3a-8afe-43e9-b757-f57f5c61f8d8"),
                            CreateBy = "Admin",
                            CreateDate = new DateTime(2024, 1, 15, 17, 8, 48, 393, DateTimeKind.Local).AddTicks(6848),
                            RoleName = "Leader",
                            UpdateBy = "Admin",
                            UpdateDate = new DateTime(2024, 1, 15, 17, 8, 48, 393, DateTimeKind.Local).AddTicks(6849)
                        },
                        new
                        {
                            RoleId = new Guid("8977ef77-e554-4ef3-8353-3e01161f84d0"),
                            CreateBy = "Admin",
                            CreateDate = new DateTime(2024, 1, 15, 17, 8, 48, 393, DateTimeKind.Local).AddTicks(6852),
                            RoleName = "Employee",
                            UpdateBy = "Admin",
                            UpdateDate = new DateTime(2024, 1, 15, 17, 8, 48, 393, DateTimeKind.Local).AddTicks(6853)
                        });
                });

            modelBuilder.Entity("Domain.Entities.ScheduleCleanSidewalk.ScheduleCleanSidewalks", b =>
                {
                    b.Property<Guid>("ScheduleCleanSidewalksId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("StreetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WorkingMonth")
                        .HasColumnType("datetime2");

                    b.HasKey("ScheduleCleanSidewalksId");

                    b.HasIndex("StreetId");

                    b.ToTable("ScheduleCleanSidewalks", (string)null);

                    b.HasData(
                        new
                        {
                            ScheduleCleanSidewalksId = new Guid("7a866c85-b013-4fab-80c7-15d21d0c686c"),
                            CreateBy = "Admin",
                            CreateDate = new DateTime(2024, 1, 15, 17, 8, 48, 393, DateTimeKind.Local).AddTicks(7437),
                            StartTime = new DateTime(2024, 1, 15, 17, 8, 48, 393, DateTimeKind.Local).AddTicks(7436),
                            StreetId = new Guid("0c0187dc-c7e2-4aa9-ae35-a5e2d60dfa24"),
                            UpdateBy = "Admin",
                            UpdateDate = new DateTime(2024, 1, 15, 17, 8, 48, 393, DateTimeKind.Local).AddTicks(7438),
                            WorkingMonth = new DateTime(2024, 1, 15, 17, 8, 48, 393, DateTimeKind.Local).AddTicks(7437)
                        });
                });

            modelBuilder.Entity("Domain.Entities.ScheduleGarbageCollect.ScheduleGarbageCollects", b =>
                {
                    b.Property<Guid>("ScheduleGarbageCollectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<float>("GabageMass")
                        .HasColumnType("real");

                    b.Property<Guid>("GarbageTruckId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("StreetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("StreetsStreetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TransitTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WorkingMonth")
                        .HasColumnType("datetime2");

                    b.HasKey("ScheduleGarbageCollectId");

                    b.HasIndex("GarbageTruckId");

                    b.HasIndex("StreetsStreetId");

                    b.ToTable("ScheduleGarbageCollects", (string)null);

                    b.HasData(
                        new
                        {
                            ScheduleGarbageCollectId = new Guid("26397b2b-ca94-4af4-bf0d-f7aaa7510698"),
                            CreateBy = "Admin",
                            CreateDate = new DateTime(2024, 1, 15, 17, 8, 48, 393, DateTimeKind.Local).AddTicks(9391),
                            GabageMass = 10f,
                            GarbageTruckId = new Guid("fc34e805-4550-4037-a273-17a0b1639bbe"),
                            StartTime = new DateTime(2024, 1, 15, 17, 8, 48, 393, DateTimeKind.Local).AddTicks(9386),
                            StreetId = new Guid("0c0187dc-c7e2-4aa9-ae35-a5e2d60dfa24"),
                            TransitTime = new DateTime(2024, 1, 15, 20, 8, 48, 393, DateTimeKind.Local).AddTicks(9387),
                            UpdateBy = "Admin",
                            UpdateDate = new DateTime(2024, 1, 15, 17, 8, 48, 393, DateTimeKind.Local).AddTicks(9391),
                            WorkingMonth = new DateTime(2024, 1, 15, 17, 8, 48, 393, DateTimeKind.Local).AddTicks(9390)
                        },
                        new
                        {
                            ScheduleGarbageCollectId = new Guid("e3c19a06-7f84-4c4d-8d83-71264a5cf176"),
                            CreateBy = "Admin",
                            CreateDate = new DateTime(2024, 1, 15, 17, 8, 48, 393, DateTimeKind.Local).AddTicks(9407),
                            GabageMass = 10f,
                            GarbageTruckId = new Guid("fc34e805-4550-4037-a273-17a0b1639bbe"),
                            StartTime = new DateTime(2024, 1, 15, 17, 8, 48, 393, DateTimeKind.Local).AddTicks(9405),
                            StreetId = new Guid("0c0187dc-c7e2-4aa9-ae35-a5e2d60dfa24"),
                            TransitTime = new DateTime(2024, 1, 15, 20, 8, 48, 393, DateTimeKind.Local).AddTicks(9406),
                            UpdateBy = "Admin",
                            UpdateDate = new DateTime(2024, 1, 15, 17, 8, 48, 393, DateTimeKind.Local).AddTicks(9407),
                            WorkingMonth = new DateTime(2024, 1, 15, 17, 8, 48, 393, DateTimeKind.Local).AddTicks(9406)
                        });
                });

            modelBuilder.Entity("Domain.Entities.ScheduleTreeTrim.ScheduleTreeTrims", b =>
                {
                    b.Property<Guid>("ScheduleTreeTrimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ActualTrimmingTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("BucketTruckId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EstimatedPruningTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("StreetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ScheduleTreeTrimId");

                    b.HasIndex("BucketTruckId");

                    b.HasIndex("StreetId");

                    b.ToTable("ScheduleTreeTrims", (string)null);

                    b.HasData(
                        new
                        {
                            ScheduleTreeTrimId = new Guid("04dc28f5-94c4-4565-93a2-934d6fee53fd"),
                            ActualTrimmingTime = new DateTime(2024, 4, 16, 17, 8, 48, 394, DateTimeKind.Local).AddTicks(1077),
                            BucketTruckId = new Guid("f9257e9f-6d30-45fd-8afc-3e3266d7adc6"),
                            CreateBy = "Admin",
                            CreateDate = new DateTime(2024, 1, 15, 17, 8, 48, 394, DateTimeKind.Local).AddTicks(1079),
                            EstimatedPruningTime = new DateTime(2024, 4, 15, 17, 8, 48, 394, DateTimeKind.Local).AddTicks(1076),
                            StreetId = new Guid("0c0187dc-c7e2-4aa9-ae35-a5e2d60dfa24"),
                            UpdateBy = "Admin",
                            UpdateDate = new DateTime(2024, 1, 15, 17, 8, 48, 394, DateTimeKind.Local).AddTicks(1080)
                        });
                });

            modelBuilder.Entity("Domain.Entities.Street.Streets", b =>
                {
                    b.Property<Guid>("StreetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumberOfHouses")
                        .HasColumnType("int");

                    b.Property<float>("StreetLength")
                        .HasColumnType("real");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("StreetTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WardId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("StreetId");

                    b.HasIndex("StreetTypeId");

                    b.HasIndex("WardId");

                    b.ToTable("Streets", (string)null);

                    b.HasData(
                        new
                        {
                            StreetId = new Guid("0c0187dc-c7e2-4aa9-ae35-a5e2d60dfa24"),
                            CreateBy = "Admin",
                            CreateDate = new DateTime(2024, 1, 15, 17, 8, 48, 394, DateTimeKind.Local).AddTicks(7900),
                            NumberOfHouses = 20,
                            StreetLength = 10000f,
                            StreetName = "Duong Huynh Lam",
                            StreetTypeId = new Guid("1be73957-b7e9-4304-9242-00e8b92a86f0"),
                            UpdateBy = "Admin",
                            UpdateDate = new DateTime(2024, 1, 15, 17, 8, 48, 394, DateTimeKind.Local).AddTicks(7901),
                            WardId = new Guid("996c63bc-5f0a-44f6-8c9a-aad741b3beac")
                        });
                });

            modelBuilder.Entity("Domain.Entities.StreetType.StreetTypes", b =>
                {
                    b.Property<Guid>("StreetTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StreetTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("StreetTypeId");

                    b.ToTable("StreetTypes", (string)null);

                    b.HasData(
                        new
                        {
                            StreetTypeId = new Guid("1be73957-b7e9-4304-9242-00e8b92a86f0"),
                            CreateBy = "Admin",
                            CreateDate = new DateTime(2024, 1, 15, 17, 8, 48, 394, DateTimeKind.Local).AddTicks(9435),
                            StreetTypeName = "Duong Kinh Doanh",
                            UpdateBy = "Admin",
                            UpdateDate = new DateTime(2024, 1, 15, 17, 8, 48, 394, DateTimeKind.Local).AddTicks(9436)
                        },
                        new
                        {
                            StreetTypeId = new Guid("e3d44b7e-8ebe-434f-88ef-054a81951be1"),
                            CreateBy = "Admin",
                            CreateDate = new DateTime(2024, 1, 15, 17, 8, 48, 394, DateTimeKind.Local).AddTicks(9447),
                            StreetTypeName = "Duong Dan Sinh",
                            UpdateBy = "Admin",
                            UpdateDate = new DateTime(2024, 1, 15, 17, 8, 48, 394, DateTimeKind.Local).AddTicks(9448)
                        });
                });

            modelBuilder.Entity("Domain.Entities.Tree.Trees", b =>
                {
                    b.Property<Guid>("TreeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("BodyDiameter")
                        .HasColumnType("real");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CultivarId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CutTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("IntervalCutTime")
                        .HasColumnType("int");

                    b.Property<float>("LeafLength")
                        .HasColumnType("real");

                    b.Property<string>("Note")
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<DateTime>("PlantTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("StreetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TreeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("TreeId");

                    b.HasIndex("CultivarId");

                    b.HasIndex("StreetId");

                    b.ToTable("Trees", (string)null);

                    b.HasData(
                        new
                        {
                            TreeId = new Guid("24b2ee45-d7c3-4cc7-9fac-406b4bac1d82"),
                            BodyDiameter = 30f,
                            CreateBy = "Admin",
                            CreateDate = new DateTime(2024, 1, 15, 17, 8, 48, 395, DateTimeKind.Local).AddTicks(821),
                            CultivarId = new Guid("136514ac-99a2-421a-80e1-5351d9a9c4af"),
                            CutTime = new DateTime(2024, 4, 15, 17, 8, 48, 395, DateTimeKind.Local).AddTicks(818),
                            IntervalCutTime = 3,
                            LeafLength = 50f,
                            Note = "",
                            PlantTime = new DateTime(2024, 1, 15, 17, 8, 48, 395, DateTimeKind.Local).AddTicks(818),
                            StreetId = new Guid("0c0187dc-c7e2-4aa9-ae35-a5e2d60dfa24"),
                            TreeCode = "12_HL_HH_NHS",
                            UpdateBy = "Admin",
                            UpdateDate = new DateTime(2024, 1, 15, 17, 8, 48, 395, DateTimeKind.Local).AddTicks(822)
                        });
                });

            modelBuilder.Entity("Domain.Entities.TreeType.TreeTypes", b =>
                {
                    b.Property<Guid>("TreeTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TreeTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("TreeTypeId");

                    b.ToTable("TreeTypes", (string)null);

                    b.HasData(
                        new
                        {
                            TreeTypeId = new Guid("ad98e780-ce3b-401b-a2ec-dd7ba8027642"),
                            CreateBy = "Admin",
                            CreateDate = new DateTime(2024, 1, 15, 17, 8, 48, 395, DateTimeKind.Local).AddTicks(2388),
                            TreeTypeName = "Cay than go",
                            UpdateBy = "Admin",
                            UpdateDate = new DateTime(2024, 1, 15, 17, 8, 48, 395, DateTimeKind.Local).AddTicks(2388)
                        });
                });

            modelBuilder.Entity("Domain.Entities.User.Users", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("56b77536-6c85-4e7d-910b-964e906c7cf2"),
                            AccessFailedCount = 0,
                            Address = "Admin",
                            ConcurrencyStamp = "c496ef12-197d-4bc4-ac33-881a84abc539",
                            DepartmentId = new Guid("bc2f24de-2b9b-489a-a108-64a114d2b9be"),
                            EmailConfirmed = false,
                            Image = "string",
                            LockoutEnabled = false,
                            Name = "Admin",
                            Password = "123123Aa!",
                            PhoneNumber = "0947346127",
                            PhoneNumberConfirmed = false,
                            RoleId = new Guid("abccde85-c7dc-4f78-9e4e-b1b3e7abee84"),
                            TwoFactorEnabled = false,
                            UserCode = "admin"
                        },
                        new
                        {
                            Id = new Guid("b2b1e0ce-0187-4285-8cce-60fdff665f46"),
                            AccessFailedCount = 0,
                            Address = "30 Nam Ky Khoi Nghia",
                            ConcurrencyStamp = "35f0855f-527c-4b19-b109-27ac61752891",
                            DepartmentId = new Guid("bc2f24de-2b9b-489a-a108-64a114d2b9be"),
                            EmailConfirmed = false,
                            Image = "string",
                            LockoutEnabled = false,
                            Name = "Nguyen Van A",
                            Password = "123123Aa!",
                            PhoneNumber = "0947123244",
                            PhoneNumberConfirmed = false,
                            RoleId = new Guid("8977ef77-e554-4ef3-8353-3e01161f84d0"),
                            TwoFactorEnabled = false,
                            UserCode = "NHS_HH_NKKN_123"
                        },
                        new
                        {
                            Id = new Guid("b2b1e0ce-0187-4285-8cce-60fdff666f46"),
                            AccessFailedCount = 0,
                            Address = "45 Huynh Lam",
                            ConcurrencyStamp = "3c59e210-faa3-474c-8908-85bc62ce7551",
                            DepartmentId = new Guid("bc2f24de-2b9b-429a-a108-64a114d2b9be"),
                            EmailConfirmed = false,
                            Image = "string",
                            LockoutEnabled = false,
                            Name = "Nguyen Van B",
                            Password = "123123Aa!",
                            PhoneNumber = "0947133244",
                            PhoneNumberConfirmed = false,
                            RoleId = new Guid("8977ef77-e554-4ef3-8353-3e01161f84d0"),
                            TwoFactorEnabled = false,
                            UserCode = "NHS_HH_NKKN_456"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Ward.Wards", b =>
                {
                    b.Property<Guid>("WardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DistrictId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WardName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("WardId");

                    b.HasIndex("DistrictId");

                    b.ToTable("Wards", (string)null);

                    b.HasData(
                        new
                        {
                            WardId = new Guid("996c63bc-5f0a-44f6-8c9a-aad741b3beac"),
                            DistrictId = new Guid("be7d62da-53ea-46b0-b294-bb109eca92fc"),
                            WardName = "Hoa Hai"
                        },
                        new
                        {
                            WardId = new Guid("faa64719-904b-4844-9ec9-d8f2620ffb51"),
                            DistrictId = new Guid("be7d62da-53ea-46b0-b294-bb109eca92fc"),
                            WardName = "Khue My"
                        },
                        new
                        {
                            WardId = new Guid("79bea4b4-23ce-41ad-b585-4dfc835d607a"),
                            DistrictId = new Guid("be7d62da-53ea-46b0-b294-bb109eca92fc"),
                            WardName = "Hoa Quy"
                        },
                        new
                        {
                            WardId = new Guid("38af1dbf-b83f-4899-8389-743021c463a0"),
                            DistrictId = new Guid("be7d62da-53ea-46b0-b294-bb109eca92fc"),
                            WardName = "My An"
                        },
                        new
                        {
                            WardId = new Guid("c088acde-18ea-48ca-ae03-bdd4e610e039"),
                            DistrictId = new Guid("be7d62da-53ea-46b0-b294-bb109eca92fc"),
                            WardName = "Hai Chau I"
                        },
                        new
                        {
                            WardId = new Guid("3097108f-15fe-4ac8-aab4-187b56841c81"),
                            DistrictId = new Guid("be7d62da-53ea-46b0-b294-bb109eca92fc"),
                            WardName = "Hai Chau II"
                        },
                        new
                        {
                            WardId = new Guid("f4e93702-9dc2-4288-8f23-4c3812ed50cc"),
                            DistrictId = new Guid("be7d62da-53ea-46b0-b294-bb109eca92fc"),
                            WardName = "Thuan Phuoc"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Cultivar.Cultivars", b =>
                {
                    b.HasOne("Domain.Entities.TreeType.TreeTypes", "TreeTypes")
                        .WithMany("Cultivars")
                        .HasForeignKey("TreeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TreeTypes");
                });

            modelBuilder.Entity("Domain.Entities.GarbageDump.GarbageDumps", b =>
                {
                    b.HasOne("Domain.Entities.Street.Streets", "Streets")
                        .WithMany("GarbageDumps")
                        .HasForeignKey("StreetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Ward.Wards", null)
                        .WithMany("GarbageDumps")
                        .HasForeignKey("WardsWardId");

                    b.Navigation("Streets");
                });

            modelBuilder.Entity("Domain.Entities.GarbageTruck.GarbageTrucks", b =>
                {
                    b.HasOne("Domain.Entities.GarbageDump.GarbageDumps", "GarbageDumps")
                        .WithMany("GarbageTrucks")
                        .HasForeignKey("GarbageDumpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.GarbageTruckType.GarbageTruckTypes", "GarbageTruckTypes")
                        .WithMany("GarbageTrucks")
                        .HasForeignKey("GarbageTruckTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GarbageDumps");

                    b.Navigation("GarbageTruckTypes");
                });

            modelBuilder.Entity("Domain.Entities.ListGarbagemanTask.ListGarbagemanTasks", b =>
                {
                    b.HasOne("Domain.Entities.ScheduleGarbageCollect.ScheduleGarbageCollects", "ScheduleGarbageCollects")
                        .WithMany("ListGarbagemanTasks")
                        .HasForeignKey("ScheduleGarbageCollectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User.Users", "Users")
                        .WithMany("ListGarbagemanTasks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScheduleGarbageCollects");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Entities.ListSidewalkCleanerTask.ListSidewalkCleanerTasks", b =>
                {
                    b.HasOne("Domain.Entities.ScheduleCleanSidewalk.ScheduleCleanSidewalks", "ScheduleCleanSidewalks")
                        .WithMany("ListSidewalkCleanerTasks")
                        .HasForeignKey("ScheduleCleanSidewalkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User.Users", "Users")
                        .WithMany("ListSidewalkCleanerTasks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScheduleCleanSidewalks");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Entities.ListTreeTrimmerTask.ListTreeTrimmerTasks", b =>
                {
                    b.HasOne("Domain.Entities.ScheduleTreeTrim.ScheduleTreeTrims", "ScheduleTreeTrims")
                        .WithMany("ListTreeTrimmerTasks")
                        .HasForeignKey("ScheduleTreeTrimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User.Users", "Users")
                        .WithMany("ListTreeTrimmerTasks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScheduleTreeTrims");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Entities.Report.Reports", b =>
                {
                    b.HasOne("Domain.Entities.User.Users", "Users")
                        .WithMany("Reports")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Entities.ScheduleCleanSidewalk.ScheduleCleanSidewalks", b =>
                {
                    b.HasOne("Domain.Entities.Street.Streets", "Streets")
                        .WithMany("ScheduleCleanSidewalks")
                        .HasForeignKey("StreetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Streets");
                });

            modelBuilder.Entity("Domain.Entities.ScheduleGarbageCollect.ScheduleGarbageCollects", b =>
                {
                    b.HasOne("Domain.Entities.GarbageTruck.GarbageTrucks", "GarbageTrucks")
                        .WithMany("ScheduleGarbageCollects")
                        .HasForeignKey("GarbageTruckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Street.Streets", "Streets")
                        .WithMany("ScheduleGarbageCollects")
                        .HasForeignKey("StreetsStreetId");

                    b.Navigation("GarbageTrucks");

                    b.Navigation("Streets");
                });

            modelBuilder.Entity("Domain.Entities.ScheduleTreeTrim.ScheduleTreeTrims", b =>
                {
                    b.HasOne("Domain.Entities.BucketTruck.BucketTrucks", "BucketTrucks")
                        .WithMany("ScheduleTreeTrims")
                        .HasForeignKey("BucketTruckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Street.Streets", "Streets")
                        .WithMany("ScheduleTreeTrims")
                        .HasForeignKey("StreetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BucketTrucks");

                    b.Navigation("Streets");
                });

            modelBuilder.Entity("Domain.Entities.Street.Streets", b =>
                {
                    b.HasOne("Domain.Entities.StreetType.StreetTypes", "StreetType")
                        .WithMany("Streets")
                        .HasForeignKey("StreetTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Ward.Wards", "Wards")
                        .WithMany("Streets")
                        .HasForeignKey("WardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StreetType");

                    b.Navigation("Wards");
                });

            modelBuilder.Entity("Domain.Entities.Tree.Trees", b =>
                {
                    b.HasOne("Domain.Entities.Cultivar.Cultivars", "Cultivar")
                        .WithMany("Trees")
                        .HasForeignKey("CultivarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Street.Streets", "Streets")
                        .WithMany("Trees")
                        .HasForeignKey("StreetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cultivar");

                    b.Navigation("Streets");
                });

            modelBuilder.Entity("Domain.Entities.User.Users", b =>
                {
                    b.HasOne("Domain.Entities.Deparment.Departments", "Departments")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Role.Roles", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departments");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Entities.Ward.Wards", b =>
                {
                    b.HasOne("Domain.Entities.District.Districts", "Districts")
                        .WithMany("Wards")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Districts");
                });

            modelBuilder.Entity("Domain.Entities.BucketTruck.BucketTrucks", b =>
                {
                    b.Navigation("ScheduleTreeTrims");
                });

            modelBuilder.Entity("Domain.Entities.Cultivar.Cultivars", b =>
                {
                    b.Navigation("Trees");
                });

            modelBuilder.Entity("Domain.Entities.Deparment.Departments", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Entities.District.Districts", b =>
                {
                    b.Navigation("Wards");
                });

            modelBuilder.Entity("Domain.Entities.GarbageDump.GarbageDumps", b =>
                {
                    b.Navigation("GarbageTrucks");
                });

            modelBuilder.Entity("Domain.Entities.GarbageTruck.GarbageTrucks", b =>
                {
                    b.Navigation("ScheduleGarbageCollects");
                });

            modelBuilder.Entity("Domain.Entities.GarbageTruckType.GarbageTruckTypes", b =>
                {
                    b.Navigation("GarbageTrucks");
                });

            modelBuilder.Entity("Domain.Entities.Role.Roles", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Entities.ScheduleCleanSidewalk.ScheduleCleanSidewalks", b =>
                {
                    b.Navigation("ListSidewalkCleanerTasks");
                });

            modelBuilder.Entity("Domain.Entities.ScheduleGarbageCollect.ScheduleGarbageCollects", b =>
                {
                    b.Navigation("ListGarbagemanTasks");
                });

            modelBuilder.Entity("Domain.Entities.ScheduleTreeTrim.ScheduleTreeTrims", b =>
                {
                    b.Navigation("ListTreeTrimmerTasks");
                });

            modelBuilder.Entity("Domain.Entities.Street.Streets", b =>
                {
                    b.Navigation("GarbageDumps");

                    b.Navigation("ScheduleCleanSidewalks");

                    b.Navigation("ScheduleGarbageCollects");

                    b.Navigation("ScheduleTreeTrims");

                    b.Navigation("Trees");
                });

            modelBuilder.Entity("Domain.Entities.StreetType.StreetTypes", b =>
                {
                    b.Navigation("Streets");
                });

            modelBuilder.Entity("Domain.Entities.TreeType.TreeTypes", b =>
                {
                    b.Navigation("Cultivars");
                });

            modelBuilder.Entity("Domain.Entities.User.Users", b =>
                {
                    b.Navigation("ListGarbagemanTasks");

                    b.Navigation("ListSidewalkCleanerTasks");

                    b.Navigation("ListTreeTrimmerTasks");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("Domain.Entities.Ward.Wards", b =>
                {
                    b.Navigation("GarbageDumps");

                    b.Navigation("Streets");
                });
#pragma warning restore 612, 618
        }
    }
}
